package tn.esprit.models;

public enum LogType {
    CONNEXION_UTILISATEUR,
    DECONNEXION_UTILISATEUR,
    AJOUT_RECLAMATION,
    MODIFIER_RECLAMATION,
    SUPPRIMER_RECLAMATION,
    AJOUT_RESERVATION,
    MODIFIER_RESERVATION,
    SUPPRIMER_RESERVATION,
}